### ISSUE TITLE
No "availabletasks" targets found.

### ISSUE THREAD

**Issue by lsiden** [ben-eb/grunt-available-tasks#20]
I installed the module and customized my Gruntfile as per instructions.

    $ grunt --help
    Grunt: The JavaScript Task Runner (v0.4.5)

    ...

    Available tasks
     availabletasks  List available Grunt tasks & targets. *                       
            connect  Start a connect web server. *                                 
             uglify  Minify files with UglifyJS. *                                 
              watch  Run predefined tasks whenever watched files change.           
         livereload  Start/Reload a LiveReload server                              
       createServer  Alias for "connect:server" task.                              
              build  Alias for "uglify:dist" task.                                 
                run  Alias for "createServer", "watch" tasks.                      

But if I try to use it, I get the above message.  Did I miss something?

**Comment by ben-eb** [comment]
You'll want to run `grunt availabletasks` instead of `grunt --help` to get this task listing. :smile:

I usually alias it with `tasks` so that you can type `grunt tasks` instead:

```js
grunt.registerTask('tasks', ['availabletasks']);
```

**Comment by lsiden** [comment]
I did run it as "grunt availabletasks".

**Comment by lsiden** [comment]
Hold the phone!  I reinstalled it and it worked.  Good work!  Thanks!
