### ISSUE TITLE
Task list empty in latest version (0.5.5)

### ISSUE THREAD

**Issue by tatablack** [ben-eb/grunt-available-tasks#21]
I guess the upgrade to Lodash and underscore.string newest versions has something to do with this: starting from 0.5.5 I don't get any output (but no errors, either).

0.5.4 still works. I'm on on node 0.10.35.

Let me know if you need more info to reproduce..

**Comment by ben-eb** [comment]
:+1:

Thanks for reporting! I didn't realise that in `3.0` you have to call `value()` at the end of a `chain()`. Would like to migrate from large utility libraries like lo-dash, but don't have the time to rewrite it at the moment. I'll push a new version to npm to fix.

**Comment by tatablack** [comment]
That was quick, thanks. :+1: :relieved:
